#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
#export _ME_ROOT="$(abs_dirname "$libexec_path")"
apath="$(abs_dirname "$libexec_path")" && \
    [ -d "$apath" ]  && [[ ":$_ME_ROOT:" != *":$apath:"* ]] && \
    { export _ME_ROOT=".:$apath:$_ME_ROOT"; }

#export PATH="${libexec_path}:$PATH"
apath="${libexec_path}:$PATH" && \
    [ -d "$apath" ]  && [[ ":$PATH:" != *":$apath:"* ]] && \
    { export PATH=".:$apath:$PATH"; }

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec sub-help
  ;;
* )
  command_path="$(command -v "sub-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "sub: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
